name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.23.x, 1.22.x] # when updating versions, update it below too.
    runs-on: ${{ matrix.os }}
    name: Test
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Test
      # TODO(henvic): Skip generating code coverage when not sending it to Coveralls to speed up testing.
      # Remove example directory from code coverage explicitly since after #26 it
      # started being considered on the code coverage report and we don't want that.
      continue-on-error: ${{ matrix.os != 'ubuntu-latest' || matrix.go != '1.23.x' }}
      run: |
        go test -race -covermode atomic -coverprofile=profile.cov ./...
        sed -i '/^github\.com\/henvic\/httpretty\/example\//d' profile.cov

    - name: Code coverage
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.go == '1.23.x' }}
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
